version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docker}
      POSTGRES_DB: "urefer"
    container_name: urefer-db
    restart: always
    ports:
      - 5432:5432
    volumes:
     - ./database-data:/var/lib/postgresql/data/