version: '3.4'

services:
  ureferfrontend:
    image: ureferfrontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
