version: '3.8'
services:
  frontend:
    container_name: urefer-frontend
    networks:
      - frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
  backend:
    container_name: urefer-backend
    networks:
      - backend
      - frontend
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on: 
      - db
    environment:
      DATABASE_URL: postgresql://postgres:docker@urefer-db:5432/urefer?schema=public
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  db:
    networks:
      - backend
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: "urefer"
    container_name: urefer-db
    restart: always
    ports:
      - 5432:5432
    volumes:
     - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
networks:
  backend:
  frontend:
