FROM node:latest
# Create app directory
WORKDIR /app
EXPOSE 5000
# Future editor beware: if you want to run a shell script from a Dockerfile,
# look at .gitattributes in this directory
CMD [ "./migrate_and_start.sh" ]
